# Generated by Django 2.1.3 on 2018-12-16 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='datum_stazeni',
        ),
        migrations.AddField(
            model_name='dokument',
            name='datum_pridani',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='foto',
            name='soubor',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='je_uvodni',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='obrazek',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='obsah',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foto',
            name='datum',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='popis',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='foto',
            name='sirka',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='obsah',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='ban',
            field=models.IntegerField(default=0),
        ),
    ]
