# Generated by Django 2.1.3 on 2018-12-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='ck_id_dokument',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='obec.Dokument'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='ck_id_foto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='obec.Foto'),
        ),
    ]
