# Generated by Django 2.1.3 on 2018-12-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obec', '0002_auto_20181217_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='ck_id_dokument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obec.Dokument'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='ck_id_foto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obec.Foto'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='ck_id_uzivatel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obec.Uzivatel'),
        ),
    ]
