# Generated by Django 2.1.3 on 2018-12-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obec', '0003_auto_20181216_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obec',
            name='erb',
            field=models.ImageField(upload_to=''),
        ),
    ]
