# Generated by Django 2.1.3 on 2018-12-17 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obec', '0005_auto_20181217_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='datum_pridani',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='foto',
            name='datum',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
