# Generated by Django 2.1.3 on 2018-12-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obec', '0006_auto_20181217_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='sirka',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
